### ISSUE TITLE
only apply ce-oem-cpu/frequency_governors for ARM platform

### ISSUE THREAD

**Issue by stanley31huang** [canonical/checkbox-provider-ce-oem#17]
### Description
The frequency_governors test is no longer valid for recently Intel CPU architecture, and this test was created for ARM architecture for purpose. So it would be better to have a `required` condition to only apply this test for ARM platform.

### Related bugs
- https://bugs.launchpad.net/austin-charlotte/+bug/2016454

**Comment by baconYao** [comment]
PR #19 is addressing this issue.
